// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCQrKHezO7sJyvnJbmZ6cp6GAkV-s5uW8',
    appId: '1:1068007125864:android:ebb4718f17392cb64d5cdd',
    messagingSenderId: '1068007125864',
    projectId: 'fir-b2fbf',
    databaseURL: 'https://fir-b2fbf-default-rtdb.firebaseio.com',
    storageBucket: 'fir-b2fbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYyQLjUgAdX5GN7VZkaEwrcRLb65shCg',
    appId: '1:1068007125864:ios:b5081c0b449d3f254d5cdd',
    messagingSenderId: '1068007125864',
    projectId: 'fir-b2fbf',
    databaseURL: 'https://fir-b2fbf-default-rtdb.firebaseio.com',
    storageBucket: 'fir-b2fbf.firebasestorage.app',
    iosBundleId: 'com.devam.chatgo',
  );
}
